# Simple docker-compose file which sets up all needed backing services
# Note that for the broker, the default credentials are ` intersect_username / intersect_password `
# NOTE: DOES NOT CONTAIN APPLICATION, ONLY BACKING SERVICES

services:
  broker_1:
    image: "bitnami/rabbitmq:3.13.3"
    #network_mode: host
    ports:
      - "1883:1883" # MQTT port
      - "5672:5672" # AMQP port
      - "15672:15672" # Web UI
    environment:
      # full list of env variables available at https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/README.md
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  # add 1 to each port number for the second broker
  broker_2:
    image: "bitnami/rabbitmq:3.13.3"
    ports:
      - "1884:1883" # MQTT port
      - "5673:5672" # AMQP port
      - "15673:15672" # Web UI
    environment:
      # full list of env variables available at https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/README.md
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  # you probably don't need this, but adding this just in case it makes local development easier
  #minio:
    #image: "bitnami/minio:2024.6.4"
    #environment:
      # references: https://github.com/bitnami/containers/blob/main/bitnami/minio/README.md
      #MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      #MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    #ports:
      #- "9000:9000" # main MINIO API port
      #- "9001:9001" # web UI
    #volumes:
      #- "./tmp/minio:/bitnami/minio/data"
