apiVersion: v2
name: broker-2-http
description: "Subscribe to broker messages and broadcast them to HTTP listeners"
version: 0.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: "^2.9.1"
