# Default values.
# most of this structure is consistent with Bitnami's, but there are no RBAC or persistence values.

# global values used by this chart
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  kubeVersion: ""

### Generic Kubernetes parameters ###

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
extraDeploy: [] # dynamic Kubernetes templates
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

### Container params ###

image:
  registry: ghcr.io
  repository: intersect-sdk/broker-http-proxy/http-2-broker
  tag: "latest"
  digest: ""
  pullPolicy: ""
  pullSecrets: []

replicaCount: 1

#livenessProbe: # the application developers should help determine sane default params
  #enabled: true
  #initialDelaySeconds: 30
  #periodSeconds: 5
  #timeoutSeconds: 10
  #failureThreshold: 6
  #successThreshold: 1

#readinessProbe: # the application developers should help determine sane default params
  #enabled: true
  #initialDelaySeconds: 5
  #timeoutSeconds: 3
  #periodSeconds: 5
  #failureThreshold: 3
  #successThreshold: 1

#startupProbe: # the application developers should help determine sane default params
  #enabled: false
  #initialDelaySeconds: 30
  #periodSeconds: 5
  #timeoutSeconds: 10
  #failureThreshold: 6
  #successThreshold: 1

customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}

resources:
  limits: {}
  requests: {}

# TODO this probably has to be configured based on the system
podSecurityContext:
  enabled: false
  fsGroup: 1001
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: false

command: []
args: []
hostAliases: []
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft

pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""
autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetCPUUtilizationPercentage: ""
  targetMemoryUtilizationPercentage: ""
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
updateStrategy:
  type: RollingUpdate
priorityClassName: ""
topologySpreadConstraints: []
schedulerName: ""
terminationGracePeriodSeconds: ""
lifecycleHooks: {}
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
initContainers: []
sidecars: []

### Kubernetes role stuff

serviceAccount:
  create: false
  annotations: {}
  name: ""
  automountServiceAccountToken: true

### application stuff

app:
  log_level: "info"
  other_proxy:
    url: "" # this should be the complete URL
    username: "" # needed credential for clients calling HTTP endpoints other than /healthcheck
    password: "" # needed credential for clients calling HTTP endpoints other than /healthcheck
  broker:
    host: "127.0.0.1"
    port: "5672"
    username: ""
    password:
      isSecret: false
      hardcoded: ""
      secretName: ""
      secretKey: ""



