[package]
name = "intersect-ingress-proxy-common"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
amqprs = { workspace = true }
async-stream = { workspace = true }
config = { workspace = true }
deadpool-amqprs = { workspace = true }
futures = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde-aux = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
